const themeDefault = {
    primaryDark: '#0D0C1D',
    primaryLight: '#EFFFFA',
    primaryHover: '#343078',
    mobile: '576px',
    colors: {
      primary: '#d40030',
      primary_dark: '#9a000a',
      primary_light: '#ff4d76',
      secondary: '#746e69',
      secondary_dark: '#48433e',
      secondary_light: '#a39c97',
      surface: '#ffffff',
      background: '#ffffff',
      error: '#B00020',
      typography: '#ffffff',
      typographyDark: '#ffffff',
      typographyLight: '#ffffff',
      iconography: '#000000',
      contained: '#B00020',
      boxBackground: '#B00020',
      boxBackgroundActive: '#746e69',
      button: '#0066ff',
      buttonBackground: '#d40030',
      graphicBackground: '#f2f2f2',
    },
    typograph: {
      fontFamily: 'Roboto',
      color: '#ffffff',
      colorDark: '#000000',
      fontSize: '1rem',
      fontWeight: '400',
      letterSpacing: '0.009rem',
      headline_1: {
        fontSize: '6rem',
        fontWeight: '400',
        letterSpacing: '-0.094rem',
      },
      headline_2: {
        fontSize: '3.75rem',
        fontWeight: '300',
        letterSpacing: '-0.031rem',
      },
      headline_3: {
        fontSize: '3rem',
        fontWeight: '400',
        letterSpacing: '0rem',
      },
      headline_4: {
        fontSize: '2.125rem',
        fontWeight: '400',
        letterSpacing: '0.016rem',
      },
      headline_5: {
        fontSize: '1.5rem',
        fontWeight: '400',
        letterSpacing: '0rem',
      },
      headline_6: {
        fontSize: '1.25rem',
        fontWeight: '500',
        letterSpacing: '0.009rem',
      },
      subtitle_1: {
        fontSize: '1rem',
        fontWeight: '400',
        letterSpacing: '0.009rem',
      },
      subtitle_2: {
        fontSize: '0.875rem',
        fontWeight: '500',
        letterSpacing: '0.001rem',
      },
      body_1: {
        fontSize: '1rem',
        fontWeight: '400',
        letterSpacing: '0.031rem',
      },
      body_2: {
        fontSize: '0.875rem',
        fontWeight: '400',
        letterSpacing: '0.016rem',
      },
      caption: {
        fontSize: '0.75rem',
        fontWeight: '400',
        letterSpacing: '0.025rem',
      },
      overline: {
        fontSize: '0.625rem',
        fontWeight: '400',
        letterSpacing: '0.094rem',
      },
    },
    grid: {
      spacing: '4px',
    },
  };
  
  export default themeDefault;